name:                codd
version:             0.1.0.0
github:              "mzabani/codd"
license:             BSD3
author:              "Marcelo Zabani"
maintainer:          "mzabani@gmail.com"
copyright:           "2021 Marcelo Zabani"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mzabani/codd#readme>

dependencies:
- base >= 4.7 && < 5
- monad-logger
- postgresql-simple
- text

ghc-options:
  - -O2

default-extensions:
  - BangPatterns
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - LambdaCase
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - TypeFamilies
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilyDependencies
  - ViewPatterns

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Werror
  dependencies:
    - aeson
    - attoparsec
    - bytestring
    - containers
    - filepath
    - hashable
    - haxl
    - mtl
    - postgresql-libpq
    - resourcet
    - streaming
    - text
    - time
    - unliftio
    - unliftio-core

executables:
  codd:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Werror
    dependencies:
    - codd
    - optparse-applicative
    - text
    - time

tests:
  codd-test: 
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wunused-packages
    # Until https://github.com/input-output-hk/haskell.nix/issues/231 is resolved,
    # do not include hspec-discover in system-build-tools. We hack around the issue
    # in default.nix so both cabal and nix-build work.
    # system-build-tools:
    # - hspec-discover
    dependencies:
    - attoparsec
    - codd
    - containers
    - hspec
    - hspec-core
    - hspec-expectations
    - mtl
    - QuickCheck
    - random
    - resourcet
    - streaming
    - time
    - unliftio
