resolver: lts-22.43

packages:
- .

extra-deps:
  - git: https://github.com/facebook/Haxl.git
    commit: 6cd30c084debcde9bb83e0f517bbe98cdd80e945
    # nix-sha256: sha256-/P44enZEdgbhULD/3eFNnSinSFlwqXfmvLHDISHBceM=

flags:
  hashable:
    random-initial-seed: true
  postgresql-libpq:
    use-pkg-config: true
