#!/usr/bin/env bash

# Runs the supplied command piping both stdout and stderr to a file and generates a github actions
# CI annotation pointing to that file if the command failed (and also exits with the same exit status)
# First argument is file to pipe to, rest is the command

# Script generated by ChatGPT (finally doing something useful) and slightly modified by me

set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <output_file> <command> [args...]" >&2
  exit 1
fi

OUTPUT_FILE="$1"
shift
COMMAND=("$@")

"${COMMAND[@]}" 2>&1 | tee "$OUTPUT_FILE"
STATUS=$?

if [[ $STATUS -ne 0 ]]; then
  # See docs at https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#setting-an-error-message
  echo "::error file=$OUTPUT_FILE::Command failed with exit code $STATUS. See log for details."
fi

exit $STATUS
